version: '2'

services:
  web:
    build: src/web
    command: -gen-addr=linkerd:4140 -word-addr=linkerd:4140

  web2:
    build: src/web
    command: -gen-addr=linkerd:4140 -word-addr=linkerd:4140
  gen:
    build: src/gen
#    container_name: gen2
#    ports: ["8181:8181"]

  gen2:
    build: src/gen
#    container_name: gen2
    ports: ["8182:8181"]
  word:
    build: src/word
    container_name: word
    ports: ["8282:8282"]

  word2:
    build: src/word
  linkerd:
    image: buoyantio/linkerd:0.7.0
    container_name: linkerd
    ports: ["4140:4140", "9990:9990"]
    volumes: ["./config:/io.buoyant/linkerd/config:ro"]
    command: /io.buoyant/linkerd/config/linkerd.yml

  namerd:
    image: buoyantio/namerd:0.7.0
    container_name: namerd
    ports: ["4100:4100", "4180:4180", "9991:9991"]
    volumes: ["./config:/io.buoyant/linkerd/config:ro"]
    command: /io.buoyant/linkerd/config/namerd.yml
