version: '2'

services:
  client:
    build: client

  server:
    build: server
    ports: 
      -  "50051:50051"

  linkerd:
    image: buoyantio/linkerd:0.7.0
    container_name: linkerd
    ports: ["4140:4140", "9990:9990"]
    volumes: ["./config:/io.buoyant/linkerd/config:ro"]
    command: /io.buoyant/linkerd/config/linkerd.yml

  namerd:
    image: buoyantio/namerd:0.7.0
    container_name: namerd
    ports: ["4100:4100", "4180:4180", "9991:9991"]
    volumes: ["./config:/io.buoyant/linkerd/config:ro"]
    command: /io.buoyant/linkerd/config/namerd.yml
